package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Ebba de Groot
 */
public class AddEmployeeView extends javax.swing.JFrame {

    /**
     * Creates new form AddEmployeeView
     */
    public AddEmployeeView() {
        initComponents();
    }

    public JButton getAddEmpBtn() {
        return addEmpBtn;
    }

    public void setAddEmpBtn(JButton addEmpBtn) {
        this.addEmpBtn = addEmpBtn;
    }

    public JTextField getCellTxt() {
        return cellTxt;
    }

    public void setCellTxt(JTextField cellTxt) {
        this.cellTxt = cellTxt;
    }

    public JTextField getCityTxt() {
        return cityTxt;
    }

    public void setCityTxt(JTextField cityTxt) {
        this.cityTxt = cityTxt;
    }

    public JButton getClearAllBtn() {
        return clearAllBtn;
    }

    public void setClearAllBtn(JButton clearAllBtn) {
        this.clearAllBtn = clearAllBtn;
    }

    public JTextField getCountryTxt() {
        return countryTxt;
    }

    public void setCountryTxt(JTextField countryTxt) {
        this.countryTxt = countryTxt;
    }

    public JTextField getDobTxt() {
        return dobTxt;
    }

    public void setDobTxt(JTextField dobTxt) {
        this.dobTxt = dobTxt;
    }

    public JTextField getEmailTxt() {
        return emailTxt;
    }

    public void setEmailTxt(JTextField emailTxt) {
        this.emailTxt = emailTxt;
    }

    public JTextField getFnameTxt() {
        return fnameTxt;
    }

    public void setFnameTxt(JTextField fnameTxt) {
        this.fnameTxt = fnameTxt;
    }

    public JTextField getLnameTxt() {
        return lnameTxt;
    }

    public void setLnameTxt(JTextField lnameTxt) {
        this.lnameTxt = lnameTxt;
    }

    public JTextField getPhoneTxt() {
        return phoneTxt;
    }

    public void setPhoneTxt(JTextField phoneTxt) {
        this.phoneTxt = phoneTxt;
    }

    public JTextField getPositionTxt() {
        return positionTxt;
    }

    public void setPositionTxt(JTextField positionTxt) {
        this.positionTxt = positionTxt;
    }

    public JTextField getPostalTxt() {
        return postalTxt;
    }

    public void setPostalTxt(JTextField postalTxt) {
        this.postalTxt = postalTxt;
    }

    public JTextField getRoleTxt() {
        return roleTxt;
    }

    public void setRoleTxt(JTextField roleTxt) {
        this.roleTxt = roleTxt;
    }

    public JTextField getSalaryTxt() {
        return salaryTxt;
    }

    public void setSalaryTxt(JTextField salaryTxt) {
        this.salaryTxt = salaryTxt;
    }

    public JTextField getSinTxt() {
        return sinTxt;
    }

    public void setSinTxt(JTextField sinTxt) {
        this.sinTxt = sinTxt;
    }

    public JTextField getStatusTxt() {
        return statusTxt;
    }

    public void setStatusTxt(JTextField statusTxt) {
        this.statusTxt = statusTxt;
    }

    public JTextField getStreetTxt() {
        return streetTxt;
    }

    public void setStreetTxt(JTextField streetTxt) {
        this.streetTxt = streetTxt;
    }

    public JTextField getUnitTxt() {
        return unitTxt;
    }

    public void setUnitTxt(JTextField unitTxt) {
        this.unitTxt = unitTxt;
    }
    
    public void addEmpBtnActionListener(ActionListener myActionListener) {
        addEmpBtn.addActionListener(myActionListener);
    }
    
    public void clearAllBtnActionListener(ActionListener myActionListener) {
        clearAllBtn.addActionListener(myActionListener);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fnameLbl = new javax.swing.JLabel();
        fnameTxt = new javax.swing.JTextField();
        lnameLbl = new javax.swing.JLabel();
        lnameTxt = new javax.swing.JTextField();
        dobLbl = new javax.swing.JLabel();
        dobTxt = new javax.swing.JTextField();
        emailLbl = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        sinLbl = new javax.swing.JLabel();
        sinTxt = new javax.swing.JTextField();
        statusLbl = new javax.swing.JLabel();
        statusTxt = new javax.swing.JTextField();
        phoneLbl = new javax.swing.JLabel();
        phoneTxt = new javax.swing.JTextField();
        cellLbl = new javax.swing.JLabel();
        cellTxt = new javax.swing.JTextField();
        unitTxt = new javax.swing.JTextField();
        unitLbl = new javax.swing.JLabel();
        streetLbl = new javax.swing.JLabel();
        streetTxt = new javax.swing.JTextField();
        cityLbl = new javax.swing.JLabel();
        cityTxt = new javax.swing.JTextField();
        postalLbl = new javax.swing.JLabel();
        postalTxt = new javax.swing.JTextField();
        countryLbl = new javax.swing.JLabel();
        countryTxt = new javax.swing.JTextField();
        positionLbl = new javax.swing.JLabel();
        positionTxt = new javax.swing.JTextField();
        salaryLbl = new javax.swing.JLabel();
        salaryTxt = new javax.swing.JTextField();
        roleLbl = new javax.swing.JLabel();
        roleTxt = new javax.swing.JTextField();
        addEmpBtn = new javax.swing.JButton();
        clearAllBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Employee");

        fnameLbl.setText("First Name:");

        lnameLbl.setText("Last Name:");

        dobLbl.setText("DOB (YYYY-MM-DD):");

        emailLbl.setText("Email:");

        sinLbl.setText("SIN:");

        statusLbl.setText("Status:");

        phoneLbl.setText("Phone:");

        cellLbl.setText("Cell:");

        unitLbl.setText("Unit Number:");

        streetLbl.setText("Street Address:");

        cityLbl.setText("City:");

        postalLbl.setText("Postal Code:");

        countryLbl.setText("Country:");

        positionLbl.setText("Position:");

        salaryLbl.setText("Salary:");

        roleLbl.setText("Role:");

        addEmpBtn.setText("Add Employee");

        clearAllBtn.setText("Clear All");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(roleLbl)
                    .addComponent(salaryLbl)
                    .addComponent(positionLbl)
                    .addComponent(countryLbl)
                    .addComponent(postalLbl)
                    .addComponent(cityLbl)
                    .addComponent(streetLbl)
                    .addComponent(cellLbl)
                    .addComponent(phoneLbl)
                    .addComponent(statusLbl)
                    .addComponent(sinLbl)
                    .addComponent(emailLbl)
                    .addComponent(dobLbl)
                    .addComponent(lnameLbl)
                    .addComponent(fnameLbl)
                    .addComponent(unitLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addEmpBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearAllBtn))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(fnameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                        .addComponent(lnameTxt)
                        .addComponent(dobTxt)
                        .addComponent(emailTxt)
                        .addComponent(sinTxt)
                        .addComponent(statusTxt)
                        .addComponent(phoneTxt)
                        .addComponent(cellTxt)
                        .addComponent(unitTxt)
                        .addComponent(streetTxt)
                        .addComponent(cityTxt)
                        .addComponent(postalTxt)
                        .addComponent(countryTxt)
                        .addComponent(positionTxt)
                        .addComponent(salaryTxt)
                        .addComponent(roleTxt)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnameLbl)
                    .addComponent(fnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnameLbl)
                    .addComponent(lnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dobLbl)
                    .addComponent(dobTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLbl)
                    .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sinLbl)
                    .addComponent(sinTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusLbl)
                    .addComponent(statusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLbl)
                    .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cellLbl)
                    .addComponent(cellTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unitLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(streetLbl)
                    .addComponent(streetTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityLbl)
                    .addComponent(cityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(postalLbl)
                    .addComponent(postalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(countryLbl)
                    .addComponent(countryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(positionLbl)
                    .addComponent(positionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salaryLbl)
                    .addComponent(salaryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roleLbl)
                    .addComponent(roleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addEmpBtn)
                    .addComponent(clearAllBtn))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployeeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmpBtn;
    private javax.swing.JLabel cellLbl;
    private javax.swing.JTextField cellTxt;
    private javax.swing.JLabel cityLbl;
    private javax.swing.JTextField cityTxt;
    private javax.swing.JButton clearAllBtn;
    private javax.swing.JLabel countryLbl;
    private javax.swing.JTextField countryTxt;
    private javax.swing.JLabel dobLbl;
    private javax.swing.JTextField dobTxt;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel fnameLbl;
    private javax.swing.JTextField fnameTxt;
    private javax.swing.JLabel lnameLbl;
    private javax.swing.JTextField lnameTxt;
    private javax.swing.JLabel phoneLbl;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JLabel positionLbl;
    private javax.swing.JTextField positionTxt;
    private javax.swing.JLabel postalLbl;
    private javax.swing.JTextField postalTxt;
    private javax.swing.JLabel roleLbl;
    private javax.swing.JTextField roleTxt;
    private javax.swing.JLabel salaryLbl;
    private javax.swing.JTextField salaryTxt;
    private javax.swing.JLabel sinLbl;
    private javax.swing.JTextField sinTxt;
    private javax.swing.JLabel statusLbl;
    private javax.swing.JTextField statusTxt;
    private javax.swing.JLabel streetLbl;
    private javax.swing.JTextField streetTxt;
    private javax.swing.JLabel unitLbl;
    private javax.swing.JTextField unitTxt;
    // End of variables declaration//GEN-END:variables
}
