package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Ebba de Groot
 */
public class AddFlightView extends javax.swing.JFrame {

    /**
     * Creates new form AddFlightView
     */
    public AddFlightView() {
        initComponents();
    }

    public JButton getAddFlightBtn() {
        return addFlightBtn;
    }

    public void setAddFlightBtn(JButton addFlightBtn) {
        this.addFlightBtn = addFlightBtn;
    }

    public JLabel getAirlineLbl() {
        return airlineLbl;
    }

    public void setAirlineLbl(JLabel airlineLbl) {
        this.airlineLbl = airlineLbl;
    }

    public JTextField getAirlineTxt() {
        return airlineTxt;
    }

    public void setAirlineTxt(JTextField airlineTxt) {
        this.airlineTxt = airlineTxt;
    }

    public JLabel getArrivalLbl() {
        return arrivalLbl;
    }

    public void setArrivalLbl(JLabel arrivalLbl) {
        this.arrivalLbl = arrivalLbl;
    }

    public JTextField getArrivalTxt() {
        return arrivalTxt;
    }

    public void setArrivalTxt(JTextField arrivalTxt) {
        this.arrivalTxt = arrivalTxt;
    }

    public JButton getClearAllBtn() {
        return clearAllBtn;
    }

    public void setClearAllBtn(JButton clearAllBtn) {
        this.clearAllBtn = clearAllBtn;
    }

    public JLabel getDepartureLbl() {
        return departureLbl;
    }

    public void setDepartureLbl(JLabel departureLbl) {
        this.departureLbl = departureLbl;
    }

    public JTextField getDepartureTxt() {
        return departureTxt;
    }

    public void setDepartureTxt(JTextField departureTxt) {
        this.departureTxt = departureTxt;
    }

    public JLabel getFlightNumLbl() {
        return flightNumLbl;
    }

    public void setFlightNumLbl(JLabel flightNumLbl) {
        this.flightNumLbl = flightNumLbl;
    }

    public JTextField getFlightNumTxt() {
        return flightNumTxt;
    }

    public void setFlightNumTxt(JTextField flightNumTxt) {
        this.flightNumTxt = flightNumTxt;
    }

    public JLabel getPriceLbl() {
        return priceLbl;
    }

    public void setPriceLbl(JLabel priceLbl) {
        this.priceLbl = priceLbl;
    }

    public JTextField getPriceTxt() {
        return priceTxt;
    }

    public void setPriceTxt(JTextField priceTxt) {
        this.priceTxt = priceTxt;
    }

    public JLabel getSeatLbl() {
        return seatLbl;
    }

    public void setSeatLbl(JLabel seatLbl) {
        this.seatLbl = seatLbl;
    }

    public JTextField getSeatTxt() {
        return seatTxt;
    }

    public void setSeatTxt(JTextField seatTxt) {
        this.seatTxt = seatTxt;
    }

    public JLabel getStatusLbl() {
        return statusLbl;
    }

    public void setStatusLbl(JLabel statusLbl) {
        this.statusLbl = statusLbl;
    }

    public JTextField getStatusTxt() {
        return statusTxt;
    }

    public void setStatusTxt(JTextField statusTxt) {
        this.statusTxt = statusTxt;
    }

    public JLabel getTripIdLbl() {
        return tripIdLbl;
    }

    public void setTripIdLbl(JLabel tripIdLbl) {
        this.tripIdLbl = tripIdLbl;
    }

    public JTextField getTripIdTxt() {
        return tripIdTxt;
    }

    public void setTripIdTxt(JTextField tripIdTxt) {
        this.tripIdTxt = tripIdTxt;
    }
    
    public void addFlightBtnListener(ActionListener addBtnClick) {
        addFlightBtn.addActionListener(addBtnClick);
    }
    
    public void addClearBtnListener(ActionListener clearBtnClick) {
        clearAllBtn.addActionListener(clearBtnClick);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        airlineLbl = new javax.swing.JLabel();
        flightNumLbl = new javax.swing.JLabel();
        departureLbl = new javax.swing.JLabel();
        arrivalLbl = new javax.swing.JLabel();
        priceLbl = new javax.swing.JLabel();
        seatLbl = new javax.swing.JLabel();
        statusLbl = new javax.swing.JLabel();
        airlineTxt = new javax.swing.JTextField();
        flightNumTxt = new javax.swing.JTextField();
        departureTxt = new javax.swing.JTextField();
        arrivalTxt = new javax.swing.JTextField();
        priceTxt = new javax.swing.JTextField();
        seatTxt = new javax.swing.JTextField();
        statusTxt = new javax.swing.JTextField();
        addFlightBtn = new javax.swing.JButton();
        clearAllBtn = new javax.swing.JButton();
        tripIdLbl = new javax.swing.JLabel();
        tripIdTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Flight");

        airlineLbl.setText("Airline:");

        flightNumLbl.setText("Flight Number:");

        departureLbl.setText("Departure (YYYY-MM-DD HH:MM):");

        arrivalLbl.setText("Arrival (YYYY-MM-DD HH:MM):");

        priceLbl.setText("Price:");

        seatLbl.setText("Seat Class:");

        statusLbl.setText("Status:");

        addFlightBtn.setText("Add Flight");

        clearAllBtn.setText("Clear All");

        tripIdLbl.setText("Trip ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tripIdLbl)
                    .addComponent(flightNumLbl)
                    .addComponent(departureLbl)
                    .addComponent(airlineLbl)
                    .addComponent(arrivalLbl)
                    .addComponent(priceLbl)
                    .addComponent(seatLbl)
                    .addComponent(statusLbl))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(addFlightBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearAllBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tripIdTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(departureTxt)
                            .addComponent(flightNumTxt)
                            .addComponent(airlineTxt)
                            .addComponent(arrivalTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(priceTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(statusTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(seatTxt, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(airlineTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(airlineLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flightNumLbl)
                    .addComponent(flightNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departureLbl)
                    .addComponent(departureTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arrivalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arrivalLbl))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tripIdLbl)
                    .addComponent(tripIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addFlightBtn)
                    .addComponent(clearAllBtn))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFlightView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFlightView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFlightView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFlightView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFlightView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFlightBtn;
    private javax.swing.JLabel airlineLbl;
    private javax.swing.JTextField airlineTxt;
    private javax.swing.JLabel arrivalLbl;
    private javax.swing.JTextField arrivalTxt;
    private javax.swing.JButton clearAllBtn;
    private javax.swing.JLabel departureLbl;
    private javax.swing.JTextField departureTxt;
    private javax.swing.JLabel flightNumLbl;
    private javax.swing.JTextField flightNumTxt;
    private javax.swing.JLabel priceLbl;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JLabel seatLbl;
    private javax.swing.JTextField seatTxt;
    private javax.swing.JLabel statusLbl;
    private javax.swing.JTextField statusTxt;
    private javax.swing.JLabel tripIdLbl;
    private javax.swing.JTextField tripIdTxt;
    // End of variables declaration//GEN-END:variables
}
