package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Ebba de Groot
 */
public class AddPromoView extends javax.swing.JFrame {

    /**
     * Creates new form AddPromoView
     */
    public AddPromoView() {
        initComponents();
        setDefaultCloseOperation(AddEmployeeView.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        promoNameLbl = new javax.swing.JLabel();
        promoNameTxt = new javax.swing.JTextField();
        percentLbl = new javax.swing.JLabel();
        percentTxt = new javax.swing.JTextField();
        startLbl = new javax.swing.JLabel();
        startTxt = new javax.swing.JTextField();
        endLbl = new javax.swing.JLabel();
        endTxt = new javax.swing.JTextField();
        addPromoBtn = new javax.swing.JButton();
        clearAllBtn = new javax.swing.JButton();
        descLbl = new javax.swing.JLabel();
        descTxt = new javax.swing.JTextField();
        statusLbl = new javax.swing.JLabel();
        statusTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Promotion");

        promoNameLbl.setText("Promotion Name:");

        percentLbl.setText("Percent:");

        startLbl.setText("Start (YYYY-MM-DD):");

        endLbl.setText("End (YYYY-MM-DD):");

        addPromoBtn.setText("Add Promotion");
        addPromoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPromoBtnActionPerformed(evt);
            }
        });

        clearAllBtn.setText("Clear All");
        clearAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAllBtnActionPerformed(evt);
            }
        });

        descLbl.setText("Description:");

        statusLbl.setText("Status:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(statusLbl)
                    .addComponent(descLbl)
                    .addComponent(percentLbl)
                    .addComponent(promoNameLbl)
                    .addComponent(startLbl)
                    .addComponent(endLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(endTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(startTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(percentTxt)
                    .addComponent(promoNameTxt)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addPromoBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearAllBtn))
                    .addComponent(descTxt)
                    .addComponent(statusTxt))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(promoNameLbl)
                    .addComponent(promoNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(percentLbl)
                    .addComponent(percentTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startLbl)
                    .addComponent(startTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endLbl)
                    .addComponent(endTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descLbl)
                    .addComponent(descTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusLbl)
                    .addComponent(statusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPromoBtn)
                    .addComponent(clearAllBtn))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addPromoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPromoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addPromoBtnActionPerformed

    private void clearAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAllBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearAllBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPromoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPromoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPromoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPromoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPromoView().setVisible(true);
            }
        });
    }

    public JButton getAddPromoBtn() {
        return addPromoBtn;
    }

    public void setAddPromoBtn(JButton addPromoBtn) {
        this.addPromoBtn = addPromoBtn;
    }

    public JButton getClearAllBtn() {
        return clearAllBtn;
    }

    public void setClearAllBtn(JButton clearAllBtn) {
        this.clearAllBtn = clearAllBtn;
    }

    public JTextField getDescTxt() {
        return descTxt;
    }

    public void setDescTxt(JTextField descTxt) {
        this.descTxt = descTxt;
    }

    public JTextField getEndTxt() {
        return endTxt;
    }

    public void setEndTxt(JTextField endTxt) {
        this.endTxt = endTxt;
    }

    public JTextField getPercentTxt() {
        return percentTxt;
    }

    public void setPercentTxt(JTextField percentTxt) {
        this.percentTxt = percentTxt;
    }

    public JTextField getPromoNameTxt() {
        return promoNameTxt;
    }

    public void setPromoNameTxt(JTextField promoNameTxt) {
        this.promoNameTxt = promoNameTxt;
    }

    public JTextField getStartTxt() {
        return startTxt;
    }

    public void setStartTxt(JTextField startTxt) {
        this.startTxt = startTxt;
    }

    public JTextField getStatusTxt() {
        return statusTxt;
    }

    public void setStatusTxt(JTextField statusTxt) {
        this.statusTxt = statusTxt;
    }
    
    public void addPromoBtnActionListener(ActionListener myActionListener) {
        addPromoBtn.addActionListener(myActionListener);
    }
    
    public void clearAllBtnActionListener(ActionListener myActionListener) {
        clearAllBtn.addActionListener(myActionListener);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPromoBtn;
    private javax.swing.JButton clearAllBtn;
    private javax.swing.JLabel descLbl;
    private javax.swing.JTextField descTxt;
    private javax.swing.JLabel endLbl;
    private javax.swing.JTextField endTxt;
    private javax.swing.JLabel percentLbl;
    private javax.swing.JTextField percentTxt;
    private javax.swing.JLabel promoNameLbl;
    private javax.swing.JTextField promoNameTxt;
    private javax.swing.JLabel startLbl;
    private javax.swing.JTextField startTxt;
    private javax.swing.JLabel statusLbl;
    private javax.swing.JTextField statusTxt;
    // End of variables declaration//GEN-END:variables
}
