package view;

import controller.EmployeeController;
import controller.TripController;
import dao.EmployeeDAO;
import dao.TripDAO;
import dao.UserDAO;

/**
 *
 * @author Ebba de Groot
 */
public class AdminMainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public AdminMainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        menuBar = new javax.swing.JMenuBar();
        customerMnu = new javax.swing.JMenu();
        searchCustomerMnu = new javax.swing.JMenuItem();
        editCustomerMnu = new javax.swing.JMenuItem();
        addCustomerMnu = new javax.swing.JMenuItem();
        deleteCustomerMnu = new javax.swing.JMenuItem();
        tripMnu = new javax.swing.JMenu();
        searchTripMnu = new javax.swing.JMenuItem();
        editTripMnu = new javax.swing.JMenuItem();
        addTripMnu = new javax.swing.JMenuItem();
        deleteTripMnu = new javax.swing.JMenuItem();
        flightMnu = new javax.swing.JMenu();
        searchFlightMnu = new javax.swing.JMenuItem();
        editFlightMnu = new javax.swing.JMenuItem();
        addFlightMnu = new javax.swing.JMenuItem();
        deleteFlightMnu = new javax.swing.JMenuItem();
        promotionsMnu = new javax.swing.JMenu();
        searchPromoMnu = new javax.swing.JMenuItem();
        editPromoMnu = new javax.swing.JMenuItem();
        addPromoMnu = new javax.swing.JMenuItem();
        deletePromoMnu = new javax.swing.JMenuItem();
        employeeMnu = new javax.swing.JMenu();
        searchEmpMnu = new javax.swing.JMenuItem();
        editEmpMnu = new javax.swing.JMenuItem();
        addEmpMnu = new javax.swing.JMenuItem();
        deleteEmpMnu = new javax.swing.JMenuItem();
        bookingMnu = new javax.swing.JMenu();
        searchBookingMnu = new javax.swing.JMenuItem();
        addBookingMnu = new javax.swing.JMenuItem();
        deleteBookingMnu = new javax.swing.JMenuItem();
        addPaymentMnu = new javax.swing.JMenuItem();
        searchPaymentMnu = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Travel System");

        customerMnu.setText("Customer");

        searchCustomerMnu.setText("Search Customers");
        customerMnu.add(searchCustomerMnu);

        editCustomerMnu.setText("Edit Customer");
        customerMnu.add(editCustomerMnu);

        addCustomerMnu.setText("Add Customer");
        customerMnu.add(addCustomerMnu);

        deleteCustomerMnu.setText("Delete Customer");
        customerMnu.add(deleteCustomerMnu);

        menuBar.add(customerMnu);

        tripMnu.setText("Trip");

        searchTripMnu.setText("Search Trips");
        tripMnu.add(searchTripMnu);

        editTripMnu.setText("Edit Trip");
        tripMnu.add(editTripMnu);

        addTripMnu.setText("Add Trip");
        addTripMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTripMnuActionPerformed(evt);
            }
        });
        tripMnu.add(addTripMnu);

        deleteTripMnu.setText("Delete Trip");
        deleteTripMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTripMnuActionPerformed(evt);
            }
        });
        tripMnu.add(deleteTripMnu);

        menuBar.add(tripMnu);

        flightMnu.setText("Flight");

        searchFlightMnu.setText("Search Flights");
        flightMnu.add(searchFlightMnu);

        editFlightMnu.setText("Edit Flight");
        editFlightMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editFlightMnuActionPerformed(evt);
            }
        });
        flightMnu.add(editFlightMnu);

        addFlightMnu.setText("Add Flight");
        flightMnu.add(addFlightMnu);

        deleteFlightMnu.setText("Delete Flight");
        flightMnu.add(deleteFlightMnu);

        menuBar.add(flightMnu);

        promotionsMnu.setText("Promotion");

        searchPromoMnu.setText("Search Promotions");
        promotionsMnu.add(searchPromoMnu);

        editPromoMnu.setText("Edit Promotion");
        promotionsMnu.add(editPromoMnu);

        addPromoMnu.setText("Add Promotion");
        addPromoMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPromoMnuActionPerformed(evt);
            }
        });
        promotionsMnu.add(addPromoMnu);

        deletePromoMnu.setText("Delete Promotion");
        promotionsMnu.add(deletePromoMnu);

        menuBar.add(promotionsMnu);

        employeeMnu.setText("Employee");

        searchEmpMnu.setText("Search Employees");
        searchEmpMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEmpMnuActionPerformed(evt);
            }
        });
        employeeMnu.add(searchEmpMnu);

        editEmpMnu.setText("Edit Employee");
        editEmpMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEmpMnuActionPerformed(evt);
            }
        });
        employeeMnu.add(editEmpMnu);

        addEmpMnu.setText("Add Employee");
        addEmpMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmpMnuActionPerformed(evt);
            }
        });
        employeeMnu.add(addEmpMnu);

        deleteEmpMnu.setText("Delete Employee");
        deleteEmpMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEmpMnuActionPerformed(evt);
            }
        });
        employeeMnu.add(deleteEmpMnu);

        menuBar.add(employeeMnu);

        bookingMnu.setText("Booking");

        searchBookingMnu.setText("Search Bookings");
        bookingMnu.add(searchBookingMnu);

        addBookingMnu.setText("Add Booking");
        bookingMnu.add(addBookingMnu);

        deleteBookingMnu.setText("Delete Booking");
        bookingMnu.add(deleteBookingMnu);

        addPaymentMnu.setText("Add Payment");
        bookingMnu.add(addPaymentMnu);

        searchPaymentMnu.setText("Search Payments");
        bookingMnu.add(searchPaymentMnu);

        menuBar.add(bookingMnu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addTripMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTripMnuActionPerformed
        AddTripView addTripView = new AddTripView();
        TripDAO tripDAO = new TripDAO();
        TripController tripController = new TripController(addTripView, tripDAO);
        addTripView.setVisible(true);
    }//GEN-LAST:event_addTripMnuActionPerformed
    
    private void addPromoMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPromoMnuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addPromoMnuActionPerformed

    private void editFlightMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editFlightMnuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editFlightMnuActionPerformed

    private void searchEmpMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEmpMnuActionPerformed
        SearchEmployeeView searchEmployeeView = new SearchEmployeeView();
        EmployeeDAO employeeDao = new EmployeeDAO();
        EmployeeController SearchEmployeeController = new EmployeeController(employeeDao, searchEmployeeView);
        searchEmployeeView.setVisible(true);
    }//GEN-LAST:event_searchEmpMnuActionPerformed

    private void editEmpMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEmpMnuActionPerformed
        EditEmployeeView editEmployeeView = new EditEmployeeView();
        EmployeeDAO employeeDao = new EmployeeDAO();
        EmployeeController employeeController = new EmployeeController(employeeDao, editEmployeeView);
        editEmployeeView.setVisible(true);
    }//GEN-LAST:event_editEmpMnuActionPerformed

    private void addEmpMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmpMnuActionPerformed
        AddEmployeeView addEmployeeView = new AddEmployeeView();
        EmployeeDAO employeeDao = new EmployeeDAO();
        UserDAO userDao = new UserDAO();
        EmployeeController employeeController = new EmployeeController(employeeDao, addEmployeeView, userDao);
        addEmployeeView.setVisible(true);
    }//GEN-LAST:event_addEmpMnuActionPerformed

    private void deleteEmpMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEmpMnuActionPerformed
        DeleteEmployeeView deleteEmployeeView = new DeleteEmployeeView();
        EmployeeDAO employeeDao = new EmployeeDAO();
        EmployeeController employeeController = new EmployeeController(employeeDao, deleteEmployeeView);
        deleteEmployeeView.setVisible(true);
    }//GEN-LAST:event_deleteEmpMnuActionPerformed

    private void deleteTripMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTripMnuActionPerformed
        DeleteTripView deleteTripView = new DeleteTripView();
        TripDAO tripDAO = new TripDAO();
        TripController tripController = new TripController(deleteTripView, tripDAO);
        deleteTripView.setVisible(true);
    }//GEN-LAST:event_deleteTripMnuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addBookingMnu;
    private javax.swing.JMenuItem addCustomerMnu;
    private javax.swing.JMenuItem addEmpMnu;
    private javax.swing.JMenuItem addFlightMnu;
    private javax.swing.JMenuItem addPaymentMnu;
    private javax.swing.JMenuItem addPromoMnu;
    private javax.swing.JMenuItem addTripMnu;
    private javax.swing.JMenu bookingMnu;
    private javax.swing.JMenu customerMnu;
    private javax.swing.JMenuItem deleteBookingMnu;
    private javax.swing.JMenuItem deleteCustomerMnu;
    private javax.swing.JMenuItem deleteEmpMnu;
    private javax.swing.JMenuItem deleteFlightMnu;
    private javax.swing.JMenuItem deletePromoMnu;
    private javax.swing.JMenuItem deleteTripMnu;
    private javax.swing.JMenuItem editCustomerMnu;
    private javax.swing.JMenuItem editEmpMnu;
    private javax.swing.JMenuItem editFlightMnu;
    private javax.swing.JMenuItem editPromoMnu;
    private javax.swing.JMenuItem editTripMnu;
    private javax.swing.JMenu employeeMnu;
    private javax.swing.JMenu flightMnu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu promotionsMnu;
    private javax.swing.JMenuItem searchBookingMnu;
    private javax.swing.JMenuItem searchCustomerMnu;
    private javax.swing.JMenuItem searchEmpMnu;
    private javax.swing.JMenuItem searchFlightMnu;
    private javax.swing.JMenuItem searchPaymentMnu;
    private javax.swing.JMenuItem searchPromoMnu;
    private javax.swing.JMenuItem searchTripMnu;
    private javax.swing.JMenu tripMnu;
    // End of variables declaration//GEN-END:variables
}
