package view;

import controller.*;
import dao.*;

/**
 *
 * @author Ebba de Groot
 */
public class CustomerMainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public CustomerMainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        menuBar = new javax.swing.JMenuBar();
        tripMnu = new javax.swing.JMenu();
        searchTripMnu = new javax.swing.JMenuItem();
        promotionsMnu = new javax.swing.JMenu();
        searchPromoMnu = new javax.swing.JMenuItem();
        bookingMnu = new javax.swing.JMenu();
        searchBookingMnu = new javax.swing.JMenuItem();
        addBookingMnu = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Travel System");

        tripMnu.setText("Trip");

        searchTripMnu.setText("Search Trips");
        searchTripMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTripMnuActionPerformed(evt);
            }
        });
        tripMnu.add(searchTripMnu);

        menuBar.add(tripMnu);

        promotionsMnu.setText("Promotion");

        searchPromoMnu.setText("Search Promotions");
        searchPromoMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPromoMnuActionPerformed(evt);
            }
        });
        promotionsMnu.add(searchPromoMnu);

        menuBar.add(promotionsMnu);

        bookingMnu.setText("Booking");

        searchBookingMnu.setText("Search Bookings");
        searchBookingMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBookingMnuActionPerformed(evt);
            }
        });
        bookingMnu.add(searchBookingMnu);

        addBookingMnu.setText("Add Booking");
        addBookingMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookingMnuActionPerformed(evt);
            }
        });
        bookingMnu.add(addBookingMnu);

        menuBar.add(bookingMnu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchTripMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTripMnuActionPerformed
        SearchTripView searchTripView = new SearchTripView();
        TripDAO tripDAO = new TripDAO();
        TripController tripController = new TripController(searchTripView, tripDAO);
        searchTripView.setVisible(true);
    }//GEN-LAST:event_searchTripMnuActionPerformed

    private void searchPromoMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPromoMnuActionPerformed
        SearchPromoView searchPromoView = new SearchPromoView();
        PromotionDAO promoDAO = new PromotionDAO();
        PromotionController promoController = new PromotionController(promoDAO, searchPromoView);
        searchPromoView.setVisible(true);
    }//GEN-LAST:event_searchPromoMnuActionPerformed

    private void searchBookingMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBookingMnuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBookingMnuActionPerformed

    private void addBookingMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookingMnuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addBookingMnuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addBookingMnu;
    private javax.swing.JMenu bookingMnu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu promotionsMnu;
    private javax.swing.JMenuItem searchBookingMnu;
    private javax.swing.JMenuItem searchPromoMnu;
    private javax.swing.JMenuItem searchTripMnu;
    private javax.swing.JMenu tripMnu;
    // End of variables declaration//GEN-END:variables
}
