package view;

import controller.*;
import dao.*;



/**
 *
 * @author Ebba de Groot
 */
public class EmployeeMainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public EmployeeMainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        menuBar = new javax.swing.JMenuBar();
        customerMnu = new javax.swing.JMenu();
        searchCustomerMnu = new javax.swing.JMenuItem();
        editCustomerMnu = new javax.swing.JMenuItem();
        addCustomerMnu = new javax.swing.JMenuItem();
        deleteCustomerMnu = new javax.swing.JMenuItem();
        tripMnu = new javax.swing.JMenu();
        searchTripMnu = new javax.swing.JMenuItem();
        editTripMnu = new javax.swing.JMenuItem();
        addTripMnu = new javax.swing.JMenuItem();
        deleteTripMnu = new javax.swing.JMenuItem();
        flightMnu = new javax.swing.JMenu();
        searchFlightMnu = new javax.swing.JMenuItem();
        editFlightMnu = new javax.swing.JMenuItem();
        addFlightMnu = new javax.swing.JMenuItem();
        deleteFlightMnu = new javax.swing.JMenuItem();
        promotionsMnu = new javax.swing.JMenu();
        searchPromoMnu = new javax.swing.JMenuItem();
        editPromoMnu = new javax.swing.JMenuItem();
        addPromoMnu = new javax.swing.JMenuItem();
        deletePromoMnu = new javax.swing.JMenuItem();
        bookingMnu = new javax.swing.JMenu();
        searchBookingMnu = new javax.swing.JMenuItem();
        addBookingMnu = new javax.swing.JMenuItem();
        deleteBookingMnu = new javax.swing.JMenuItem();
        addPaymentMnu = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Travel System");

        customerMnu.setText("Customer");

        searchCustomerMnu.setText("Search Customers");
        searchCustomerMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCustomerMnuActionPerformed(evt);
            }
        });
        customerMnu.add(searchCustomerMnu);

        editCustomerMnu.setText("Edit Customer");
        editCustomerMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCustomerMnuActionPerformed(evt);
            }
        });
        customerMnu.add(editCustomerMnu);

        addCustomerMnu.setText("Add Customer");
        addCustomerMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerMnuActionPerformed(evt);
            }
        });
        customerMnu.add(addCustomerMnu);

        deleteCustomerMnu.setText("Delete Customer");
        deleteCustomerMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCustomerMnuActionPerformed(evt);
            }
        });
        customerMnu.add(deleteCustomerMnu);

        menuBar.add(customerMnu);

        tripMnu.setText("Trip");

        searchTripMnu.setText("Search Trips");
        searchTripMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTripMnuActionPerformed(evt);
            }
        });
        tripMnu.add(searchTripMnu);

        editTripMnu.setText("Edit Trip");
        editTripMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTripMnuActionPerformed(evt);
            }
        });
        tripMnu.add(editTripMnu);

        addTripMnu.setText("Add Trip");
        addTripMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTripMnuActionPerformed(evt);
            }
        });
        tripMnu.add(addTripMnu);

        deleteTripMnu.setText("Delete Trip");
        deleteTripMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTripMnuActionPerformed(evt);
            }
        });
        tripMnu.add(deleteTripMnu);

        menuBar.add(tripMnu);

        flightMnu.setText("Flight");

        searchFlightMnu.setText("Search Flights");
        searchFlightMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFlightMnuActionPerformed(evt);
            }
        });
        flightMnu.add(searchFlightMnu);

        editFlightMnu.setText("Edit Flight");
        editFlightMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editFlightMnuActionPerformed(evt);
            }
        });
        flightMnu.add(editFlightMnu);

        addFlightMnu.setText("Add Flight");
        addFlightMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFlightMnuActionPerformed(evt);
            }
        });
        flightMnu.add(addFlightMnu);

        deleteFlightMnu.setText("Delete Flight");
        deleteFlightMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFlightMnuActionPerformed(evt);
            }
        });
        flightMnu.add(deleteFlightMnu);

        menuBar.add(flightMnu);

        promotionsMnu.setText("Promotion");

        searchPromoMnu.setText("Search Promotions");
        searchPromoMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPromoMnuActionPerformed(evt);
            }
        });
        promotionsMnu.add(searchPromoMnu);

        editPromoMnu.setText("Edit Promotion");
        editPromoMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPromoMnuActionPerformed(evt);
            }
        });
        promotionsMnu.add(editPromoMnu);

        addPromoMnu.setText("Add Promotion");
        addPromoMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPromoMnuActionPerformed(evt);
            }
        });
        promotionsMnu.add(addPromoMnu);

        deletePromoMnu.setText("Delete Promotion");
        deletePromoMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePromoMnuActionPerformed(evt);
            }
        });
        promotionsMnu.add(deletePromoMnu);

        menuBar.add(promotionsMnu);

        bookingMnu.setText("Booking");

        searchBookingMnu.setText("Search Bookings");
        searchBookingMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBookingMnuActionPerformed(evt);
            }
        });
        bookingMnu.add(searchBookingMnu);

        addBookingMnu.setText("Add Booking");
        addBookingMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookingMnuActionPerformed(evt);
            }
        });
        bookingMnu.add(addBookingMnu);

        deleteBookingMnu.setText("Delete Booking");
        deleteBookingMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBookingMnuActionPerformed(evt);
            }
        });
        bookingMnu.add(deleteBookingMnu);

        addPaymentMnu.setText("Add Payment");
        addPaymentMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPaymentMnuActionPerformed(evt);
            }
        });
        bookingMnu.add(addPaymentMnu);

        menuBar.add(bookingMnu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addTripMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTripMnuActionPerformed
        AddTripView addTripView = new AddTripView();
        TripDAO tripDAO = new TripDAO();
        TripController tripController = new TripController(addTripView, tripDAO);
        addTripView.setVisible(true);
    }//GEN-LAST:event_addTripMnuActionPerformed

    private void addPromoMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPromoMnuActionPerformed
        AddPromoView promotionView = new AddPromoView();
        PromotionDAO promotionDao = new PromotionDAO();
        PromotionController promotionController = new PromotionController(promotionDao, promotionView);
        promotionView.setVisible(true);
    }//GEN-LAST:event_addPromoMnuActionPerformed

    private void editFlightMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editFlightMnuActionPerformed
        EditFlightView editFlightView = new EditFlightView();
        FlightDAO flightDAO = new FlightDAO();
        FlightController flightController = new FlightController(editFlightView, flightDAO);
        editFlightView.setVisible(true);
    }//GEN-LAST:event_editFlightMnuActionPerformed

    private void searchPromoMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPromoMnuActionPerformed
        SearchPromoView promotionView = new SearchPromoView();
        PromotionDAO promotionDao = new PromotionDAO();
        PromotionController promotionController = new PromotionController(promotionDao, promotionView);
        promotionView.setVisible(true);
    }//GEN-LAST:event_searchPromoMnuActionPerformed

    private void editPromoMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPromoMnuActionPerformed
        EditPromoView promotionView = new EditPromoView();
        PromotionDAO promotionDao = new PromotionDAO();
        PromotionController promotionController = new PromotionController(promotionDao, promotionView);
        promotionView.setVisible(true);
    }//GEN-LAST:event_editPromoMnuActionPerformed

    private void deletePromoMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePromoMnuActionPerformed
        DeletePromoView promotionView = new DeletePromoView();
        PromotionDAO promotionDao = new PromotionDAO();
        PromotionController promotionController = new PromotionController(promotionDao, promotionView);
        promotionView.setVisible(true);
    }//GEN-LAST:event_deletePromoMnuActionPerformed
    private void searchCustomerMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCustomerMnuActionPerformed
        SearchCustomerView searchCustomerView = new SearchCustomerView();
        CustomerDAO customerDAO = new CustomerDAO();
        CustomerController customerController = new CustomerController(customerDAO, searchCustomerView);
        searchCustomerView.setVisible(true);
    }//GEN-LAST:event_searchCustomerMnuActionPerformed

    private void editCustomerMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCustomerMnuActionPerformed
        EditCustomerView editCustomerView = new EditCustomerView();
        CustomerDAO customerDAO = new CustomerDAO();
        CustomerController customerController = new CustomerController(customerDAO, editCustomerView);
        editCustomerView.setVisible(true);
    }//GEN-LAST:event_editCustomerMnuActionPerformed

    private void addCustomerMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerMnuActionPerformed
        AddCustomerView addCustomerView = new AddCustomerView();
        CustomerDAO customerDAO = new CustomerDAO();
        UserDAO userDAO = new UserDAO();
        CustomerController customerController = new CustomerController(customerDAO, addCustomerView, userDAO);
        addCustomerView.setVisible(true);
    }//GEN-LAST:event_addCustomerMnuActionPerformed

    private void deleteCustomerMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCustomerMnuActionPerformed
        DeleteCustomerView deleteCustomerView = new DeleteCustomerView();
        CustomerDAO customerDAO = new CustomerDAO();
        CustomerController customerController = new CustomerController(customerDAO, deleteCustomerView);
        deleteCustomerView.setVisible(true);
    }//GEN-LAST:event_deleteCustomerMnuActionPerformed

    private void searchTripMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTripMnuActionPerformed
        SearchTripView searchTripView = new SearchTripView();
        TripDAO tripDAO = new TripDAO();
        TripController tripController = new TripController(searchTripView, tripDAO);
        searchTripView.setVisible(true);
    }//GEN-LAST:event_searchTripMnuActionPerformed

    private void editTripMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTripMnuActionPerformed
        EditTripView editTripView = new EditTripView();
        TripDAO tripDAO = new TripDAO();
        TripController tripController = new TripController(editTripView, tripDAO);
        editTripView.setVisible(true);
    }//GEN-LAST:event_editTripMnuActionPerformed

    private void deleteTripMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTripMnuActionPerformed
        DeleteTripView deleteTripView = new DeleteTripView();
        TripDAO tripDAO = new TripDAO();
        TripController tripController = new TripController(deleteTripView, tripDAO);
        deleteTripView.setVisible(true);
    }//GEN-LAST:event_deleteTripMnuActionPerformed

    private void searchFlightMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFlightMnuActionPerformed
        SearchFlightView searchFlightView = new SearchFlightView();
        FlightDAO flightDAO = new FlightDAO();
        FlightController flightController = new FlightController(searchFlightView, flightDAO);
        searchFlightView.setVisible(true);
    }//GEN-LAST:event_searchFlightMnuActionPerformed

    private void addFlightMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFlightMnuActionPerformed
        AddFlightView addFlightView = new AddFlightView();
        FlightDAO flightDAO = new FlightDAO();
        FlightController flightController = new FlightController(addFlightView, flightDAO);
        addFlightView.setVisible(true);
    }//GEN-LAST:event_addFlightMnuActionPerformed

    private void deleteFlightMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFlightMnuActionPerformed
        DeleteFlightView deleteFlightView = new DeleteFlightView();
        FlightDAO flightDAO = new FlightDAO();
        FlightController flightController = new FlightController(deleteFlightView, flightDAO);
        deleteFlightView.setVisible(true);
    }//GEN-LAST:event_deleteFlightMnuActionPerformed

    private void searchBookingMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBookingMnuActionPerformed
        SearchBookingView searchBookingView = new SearchBookingView();
        BookingDAO bookingDAO = new BookingDAO();
        BookingController bookingController = new BookingController(bookingDAO, searchBookingView);
        searchBookingView.setVisible(true);
    }//GEN-LAST:event_searchBookingMnuActionPerformed

    private void addBookingMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookingMnuActionPerformed
        AddBookingView addBookingView = new AddBookingView();
        BookingDAO bookingDAO = new BookingDAO();
        BookingController bookingController = new BookingController(bookingDAO, addBookingView);
        addBookingView.setVisible(true);
    }//GEN-LAST:event_addBookingMnuActionPerformed

    private void deleteBookingMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBookingMnuActionPerformed
        DeleteBookingView deleteBookingView = new DeleteBookingView();
        BookingDAO bookingDAO = new BookingDAO();
        BookingController bookingController = new BookingController(bookingDAO, deleteBookingView);
        deleteBookingView.setVisible(true);
    }//GEN-LAST:event_deleteBookingMnuActionPerformed

    private void addPaymentMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPaymentMnuActionPerformed
        AddPaymentView addPaymentView = new AddPaymentView();
        PaymentDAO paymentDAO = new PaymentDAO();
        PaymentController paymentController = new PaymentController(addPaymentView, paymentDAO);
        addPaymentView.setVisible(true);
    }//GEN-LAST:event_addPaymentMnuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addBookingMnu;
    private javax.swing.JMenuItem addCustomerMnu;
    private javax.swing.JMenuItem addFlightMnu;
    private javax.swing.JMenuItem addPaymentMnu;
    private javax.swing.JMenuItem addPromoMnu;
    private javax.swing.JMenuItem addTripMnu;
    private javax.swing.JMenu bookingMnu;
    private javax.swing.JMenu customerMnu;
    private javax.swing.JMenuItem deleteBookingMnu;
    private javax.swing.JMenuItem deleteCustomerMnu;
    private javax.swing.JMenuItem deleteFlightMnu;
    private javax.swing.JMenuItem deletePromoMnu;
    private javax.swing.JMenuItem deleteTripMnu;
    private javax.swing.JMenuItem editCustomerMnu;
    private javax.swing.JMenuItem editFlightMnu;
    private javax.swing.JMenuItem editPromoMnu;
    private javax.swing.JMenuItem editTripMnu;
    private javax.swing.JMenu flightMnu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu promotionsMnu;
    private javax.swing.JMenuItem searchBookingMnu;
    private javax.swing.JMenuItem searchCustomerMnu;
    private javax.swing.JMenuItem searchFlightMnu;
    private javax.swing.JMenuItem searchPromoMnu;
    private javax.swing.JMenuItem searchTripMnu;
    private javax.swing.JMenu tripMnu;
    // End of variables declaration//GEN-END:variables
}
