/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author goenchoi
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        CustomerMnu = new javax.swing.JMenu();
        addCustomerMnu = new javax.swing.JMenuItem();
        editCustomerMnu = new javax.swing.JMenuItem();
        searchCustomerMnu = new javax.swing.JMenuItem();
        addTripMnu = new javax.swing.JMenu();
        bookTripMnu = new javax.swing.JMenuItem();
        editTripMnu = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        searchFlightMnu = new javax.swing.JMenuItem();
        editFlightMnu = new javax.swing.JMenuItem();
        promotionsMnu = new javax.swing.JMenu();
        searchPromoMnu = new javax.swing.JMenuItem();
        editPromoMnu = new javax.swing.JMenuItem();
        addPromoMnu = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Travel System");

        CustomerMnu.setText("Customer");
        CustomerMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerMnuActionPerformed(evt);
            }
        });

        addCustomerMnu.setText("Add Customer");
        addCustomerMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerMnuActionPerformed(evt);
            }
        });
        CustomerMnu.add(addCustomerMnu);

        editCustomerMnu.setText("Edit Customer");
        CustomerMnu.add(editCustomerMnu);

        searchCustomerMnu.setText("Search Customer");
        CustomerMnu.add(searchCustomerMnu);

        jMenuBar1.add(CustomerMnu);

        addTripMnu.setText("Trips");

        bookTripMnu.setText("Book Trip");
        addTripMnu.add(bookTripMnu);

        editTripMnu.setText("Edit Trip");
        addTripMnu.add(editTripMnu);

        jMenuItem2.setText("Add Trip");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        addTripMnu.add(jMenuItem2);

        jMenuBar1.add(addTripMnu);

        jMenu2.setText("Flights");

        searchFlightMnu.setText("Search Flights");
        jMenu2.add(searchFlightMnu);

        editFlightMnu.setText("Edit Flights");
        editFlightMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editFlightMnuActionPerformed(evt);
            }
        });
        jMenu2.add(editFlightMnu);

        jMenuBar1.add(jMenu2);

        promotionsMnu.setText("Promotion");

        searchPromoMnu.setText("Search Promotions");
        promotionsMnu.add(searchPromoMnu);

        editPromoMnu.setText("Edit Promotion");
        promotionsMnu.add(editPromoMnu);

        addPromoMnu.setText("Add Promotion");
        addPromoMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPromoMnuActionPerformed(evt);
            }
        });
        promotionsMnu.add(addPromoMnu);

        jMenuBar1.add(promotionsMnu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void addPromoMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPromoMnuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addPromoMnuActionPerformed

    private void editFlightMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editFlightMnuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editFlightMnuActionPerformed

    private void CustomerMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerMnuActionPerformed
       
    }//GEN-LAST:event_CustomerMnuActionPerformed

    private void addCustomerMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerMnuActionPerformed
        
    }//GEN-LAST:event_addCustomerMnuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu CustomerMnu;
    private javax.swing.JMenuItem addCustomerMnu;
    private javax.swing.JMenuItem addPromoMnu;
    private javax.swing.JMenu addTripMnu;
    private javax.swing.JMenuItem bookTripMnu;
    private javax.swing.JMenuItem editCustomerMnu;
    private javax.swing.JMenuItem editFlightMnu;
    private javax.swing.JMenuItem editPromoMnu;
    private javax.swing.JMenuItem editTripMnu;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu promotionsMnu;
    private javax.swing.JMenuItem searchCustomerMnu;
    private javax.swing.JMenuItem searchFlightMnu;
    private javax.swing.JMenuItem searchPromoMnu;
    // End of variables declaration//GEN-END:variables
}
