package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Ebba de Groot
 */
public class SearchFlightView extends javax.swing.JFrame {

    /**
     * Creates new form SearchFlightView
     */
    public SearchFlightView() {
        initComponents();
    }

    public JLabel getAirlineLbl() {
        return airlineLbl;
    }

    public void setAirlineLbl(JLabel airlineLbl) {
        this.airlineLbl = airlineLbl;
    }

    public JTextField getAirlineTxt() {
        return airlineTxt;
    }

    public void setAirlineTxt(JTextField airlineTxt) {
        this.airlineTxt = airlineTxt;
    }

    public JButton getClearAllBtn() {
        return clearAllBtn;
    }

    public void setClearAllBtn(JButton clearAllBtn) {
        this.clearAllBtn = clearAllBtn;
    }

    public JLabel getFlightIdLbl() {
        return flightIdLbl;
    }

    public void setFlightIdLbl(JLabel flightIdLbl) {
        this.flightIdLbl = flightIdLbl;
    }

    public JTextField getFlightIdTxt() {
        return flightIdTxt;
    }

    public void setFlightIdTxt(JTextField flightIdTxt) {
        this.flightIdTxt = flightIdTxt;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTextArea getjTextArea1() {
        return jTextArea1;
    }

    public void setjTextArea1(JTextArea jTextArea1) {
        this.jTextArea1 = jTextArea1;
    }

    public JButton getSearchAirlineBtn() {
        return searchAirlineBtn;
    }

    public void setSearchAirlineBtn(JButton searchAirlineBtn) {
        this.searchAirlineBtn = searchAirlineBtn;
    }

    public JButton getSearchAllBtn() {
        return searchAllBtn;
    }

    public void setSearchAllBtn(JButton searchAllBtn) {
        this.searchAllBtn = searchAllBtn;
    }

    public JButton getSearchIdBtn() {
        return searchIdBtn;
    }

    public void setSearchIdBtn(JButton searchIdBtn) {
        this.searchIdBtn = searchIdBtn;
    }

    public JTable getSearchTable() {
        return searchTable;
    }
    
    public void searchIdBtnLisener(ActionListener addBtnClick) {
        searchIdBtn.addActionListener(addBtnClick);
    }
    
    public void searchAirlineBtnLisener(ActionListener addBtnClick) {
        searchAirlineBtn.addActionListener(addBtnClick);
    }
     
    public void searchAllBtnLisener(ActionListener addBtnClick) {
        searchAllBtn.addActionListener(addBtnClick);
    }
    
     public void clearAllBtnLisener(ActionListener addBtnClick) {
        clearAllBtn.addActionListener(addBtnClick);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        airlineLbl = new javax.swing.JLabel();
        airlineTxt = new javax.swing.JTextField();
        clearAllBtn = new javax.swing.JButton();
        searchAllBtn = new javax.swing.JButton();
        flightIdLbl = new javax.swing.JLabel();
        flightIdTxt = new javax.swing.JTextField();
        searchIdBtn = new javax.swing.JButton();
        searchAirlineBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        searchTable = new javax.swing.JTable();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search Flights");

        airlineLbl.setText("Airline:");

        clearAllBtn.setText("Clear All");

        searchAllBtn.setText("Search All");

        flightIdLbl.setText("Flight ID:");

        searchIdBtn.setText("Search");

        searchAirlineBtn.setText("Search");
        searchAirlineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAirlineBtnActionPerformed(evt);
            }
        });

        searchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight Id", "Trip Id", "Airline", "Flight Number", "Departure Time", "Arrival Time", "Price", "Seat Class", "Status"
            }
        ));
        jScrollPane2.setViewportView(searchTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(airlineLbl)
                            .addComponent(flightIdLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchAllBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clearAllBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(airlineTxt)
                                    .addComponent(flightIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(searchIdBtn)
                                    .addComponent(searchAirlineBtn))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flightIdLbl)
                    .addComponent(flightIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchIdBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(airlineLbl)
                    .addComponent(airlineTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchAirlineBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearAllBtn)
                    .addComponent(searchAllBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchAirlineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAirlineBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchAirlineBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchFlightView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchFlightView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchFlightView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchFlightView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchFlightView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel airlineLbl;
    private javax.swing.JTextField airlineTxt;
    private javax.swing.JButton clearAllBtn;
    private javax.swing.JLabel flightIdLbl;
    private javax.swing.JTextField flightIdTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton searchAirlineBtn;
    private javax.swing.JButton searchAllBtn;
    private javax.swing.JButton searchIdBtn;
    private javax.swing.JTable searchTable;
    // End of variables declaration//GEN-END:variables
}
