package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Ebba de Groot
 */
public class SearchPromoView extends javax.swing.JFrame {

    /**
     * Creates new form SearchPromoView
     */
    public SearchPromoView() {
        initComponents();
        setDefaultCloseOperation(SearchEmployeeView.DISPOSE_ON_CLOSE);
    }

    public JTextField getMonthTxt() {
        return monthTxt;
    }

    public void setMonthTxt(JTextField monthTxt) {
        this.monthTxt = monthTxt;
    }
    
    public JButton getClearAllBtn() {
        return clearAllBtn;
    }

    public JButton getSearchAllBtn() {
        return searchAllBtn;
    }
    
    public JButton getSearchMonthBtn() {
        return searchMonthBtn;
    }
    
    public void searchAllBtnActionListener(ActionListener myActionListener) {
        searchAllBtn.addActionListener(myActionListener);
    }
    
    public void clearAllBtnActionListener(ActionListener myActionListener) {
        clearAllBtn.addActionListener(myActionListener);
    }
    
    public void searchMonthBtnActionListener(ActionListener myActionListener) {
        searchMonthBtn.addActionListener(myActionListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        monthLbl = new javax.swing.JLabel();
        monthTxt = new javax.swing.JTextField();
        searchNameBtn = new javax.swing.JButton();
        clearAllBtn = new javax.swing.JButton();
        searchAllBtn = new javax.swing.JButton();
        promoIdLbl = new javax.swing.JLabel();
        promoNameTxt = new javax.swing.JTextField();
        searchMonthBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchPromoTbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Search Promotions");

        monthLbl.setText("Month (MMM):");

        searchNameBtn.setText("Search");
        searchNameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchNameBtnActionPerformed(evt);
            }
        });

        clearAllBtn.setText("Clear All");
        clearAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAllBtnActionPerformed(evt);
            }
        });

        searchAllBtn.setText("Search All");
        searchAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAllBtnActionPerformed(evt);
            }
        });

        promoIdLbl.setText("Promotion Name: ");

        searchMonthBtn.setText("Search");
        searchMonthBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchMonthBtnActionPerformed(evt);
            }
        });

        searchPromoTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Promotion Id", "Prmotion Name", "Discount percent", "Promotion Start Date", "Promotion End Date", "Status"
            }
        ));
        jScrollPane1.setViewportView(searchPromoTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(promoIdLbl)
                            .addComponent(monthLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchAllBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clearAllBtn)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(monthTxt)
                                .addComponent(promoNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchNameBtn)
                            .addComponent(searchMonthBtn))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(promoNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchNameBtn))
                    .addComponent(promoIdLbl, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monthLbl)
                    .addComponent(monthTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchMonthBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearAllBtn)
                    .addComponent(searchAllBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAllBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchAllBtnActionPerformed

    private void searchNameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchNameBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchNameBtnActionPerformed

    private void searchMonthBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchMonthBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchMonthBtnActionPerformed

    private void clearAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAllBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearAllBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchPromoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchPromoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchPromoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchPromoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchPromoView().setVisible(true);
            }
        });
    }

    
    public void searchNameActionListener (ActionListener myActionListener) {
        searchNameBtn.addActionListener(myActionListener);
    }

    public void setClearAllBtn(JButton clearAllBtn) {
        this.clearAllBtn = clearAllBtn;
    }

    public JTextField getPromoNameTxt() {
        return promoNameTxt;
    }

    public void setPromoNameTxt(JTextField promoNameTxt) {
        this.promoNameTxt = promoNameTxt;
    }

    public void setSearchAllBtn(JButton searchAllBtn) {
        this.searchAllBtn = searchAllBtn;
    }

    public void setSearchMonthBtn(JButton searchMonthBtn) {
        this.searchMonthBtn = searchMonthBtn;
    }

    public JButton getSearchNameBtn() {
        return searchNameBtn;
    }

    public void setSearchNameBtn(JButton searchNameBtn) {
        this.searchNameBtn = searchNameBtn;
    }

    public JTable getSearchPromoTbl() {
        return searchPromoTbl;
    }

    public void setSearchPromoTbl(JTable searchPromoTbl) {
        this.searchPromoTbl = searchPromoTbl;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearAllBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel monthLbl;
    private javax.swing.JTextField monthTxt;
    private javax.swing.JLabel promoIdLbl;
    private javax.swing.JTextField promoNameTxt;
    private javax.swing.JButton searchAllBtn;
    private javax.swing.JButton searchMonthBtn;
    private javax.swing.JButton searchNameBtn;
    private javax.swing.JTable searchPromoTbl;
    // End of variables declaration//GEN-END:variables
}
